language: python

matrix:
  include:
    - os: linux
      python: 3.6 

    - os: osx
      language: generic


install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.

  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;

    else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;

    fi
    
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n cudatool python=3.6 conda-build numba conda-verify
  - source activate cudatool
  
script:
  - conda-build condarecipe9.2
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        conda install --use-local $CONDA_PREFIX/conda-bld/osx-64/cudatoolkit-dev-9.2-0.tar.bz2 -v;
    else
        conda install --use-local $CONDA_PREFIX/conda-bld/linux-64/cudatoolkit-dev-9.2-0.tar.bz2 -v;
    fi
  - ls $CONDA_PREFIX/pkgs/cudatoolkit-dev
  - python tests/run_test.py

notifications:
  email: false
