version: 2
jobs:
  conda:
    docker:
      - image: condaforge/linux-anvil
    steps:
      - checkout
      - run: export PATH="/opt/conda/bin:${PATH}"  
      - run: export PATH="/opt/conda/bin:${PATH}" && conda config --set always_yes yes --set changeps1 no && conda update -q conda && conda create -n cuda-test python=3.6 conda-build
      - run: export PATH="/opt/conda/bin:${PATH}" && source activate cuda-test && conda-build condarecipe9.2 && conda install --use-local $CONDA_PREFIX/conda-bld/linux-64/cudatoolkit-dev-9.2-0.tar.bz2 -v && source deactivate
      - run: export PATH="/opt/conda/bin:${PATH}" && source activate cuda-test && ls $CONDA_PREFIX/pkgs/cudatoolkit-dev-9.2-0
      - run: export PATH="/opt/conda/bin:${PATH}" && source activate cuda-test && ls $CONDA_PREFIX/bin && echo $CUDA_HOME && which nvcc
workflows:
  version: 2
  test:
    jobs:
      - conda